### ISSUE TITLE
Error on DirectoryInfo.GetFileSystemInfos() with drives that are mounted to NTFS

### ISSUE THREAD

**Issue by meccoro** [alphaleonis/AlphaFS#172] opened 2015-06-10 05:39 UTC
## environment
- OS : Windows7 64bit Professional
- .NET : 3.5
- AlpaFS : [2.0.1](https://github.com/alphaleonis/AlphaFS/releases/tag/v2.0.1)
## current behavior

For drives that are mounted to NTFS, you can use the following methods, an error is thrown
- Alphaleonis.Win32.Filesystem.DirectoryInfo.GetFileSystemInfos() 

stacktrace

> Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath) d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\NativeError.cs:行 93
> Alphaleonis.Win32.NativeError.ThrowException(Int32 errorCode, String readPath) d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\NativeError.cs:行 52
> Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.FindFirstFile(String pathLp, Win32FindData& win32FindData) d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:行 117
> Alphaleonis.Win32.Filesystem.FindFileSystemEntryInfo.<Enumerate>d__3`1.MoveNext() d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\FindFileSystemEntryInfo.cs:行 205
> System.Linq.Buffer`1..ctor(IEnumerable`1 source)
> System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
> Alphaleonis.Win32.Filesystem.DirectoryInfo.GetFileSystemInfos() d:\Coding\Projects\GitHub\AlphaFS\AlphaFS\Filesystem\DirectoryInfo Class\DirectoryInfo.GetFileSystemInfos.cs:行 48
## sorce code

`DirectoryInfo directoryInfo = new DirectoryInfo(path);`
`directoryInfo.GetFileSystemInfos();`
## expectation

error is not thrown
## notes

No error is thrown by the following methods
[System.IO.DirectoryInfo.GetFileSystemInfos()](https://msdn.microsoft.com/en-us/library/806sc8c5%28v=vs.110%29.aspx)

Could you help me ?
meccoro

**Comment by Yomodo** [comment] 2015-06-10 08:46
What does `path` look like?
Do you mean mounted drives as in attached USB sticks/drives with NTFS?

**Comment by meccoro** [comment] 2015-06-11 12:48
## step
- 1 there is a volume that is formatted with NTFS (H:¥)
- 2 create an empty folder “aaa” (H:¥aaa)
- 3 create a "simple volume" from the "Disk Management"
- 4 specify the following in the "drive letter or, allocation of path”<br>
  mount an empty NTFS folder<br>
  H:¥aaa<br>
- like this<br>
  `DirectoryInfo directoryInfo = new DirectoryInfo(H:¥aaa)`
  `directoryInfo.GetFileSystemInfos();`

Could you help me ?<br>
meccoro

**Comment by Yomodo** [comment] 2016-09-02 23:53
@meccoro Could you try again with our latest develop build to see if the issue is still present?

**Comment by Yomodo** [comment] 2016-09-29 06:57
This is a duplicate of #41.

**Closed as completed by Yomodo** 2016-09-29 06:57 UTC
Labels: Won't Fix

**Comment by meccoro** [comment] 2016-09-29 08:38
hello

Thank you for your reply.
It was reproduced in the following versions.
https://github.com/alphaleonis/AlphaFS/releases/tag/v2.0.1

2016-09-03 8:53 GMT+09:00 Jeffrey Jangli notifications@github.com:

**Comment by Yomodo** [comment] 2016-09-29 08:41
This issue is the same as #41.  There was no solution to be found and, unfortunately, there's still no solution for this issue.
